### ISSUE TITLE
Forest of Tethyr Patch for CtB

### ISSUE THREAD

**Issue by Endarire** [RoxanneSHS/CtB-EE-Modules#1]
@RoxanneSHS 
Greetings!

Does your version of CtB include the [Forest of Tethyr patch](http://www.shsforums.net/files/file/855-tethyr-forest-patch-version-3b-112609/)?  If not, may we get it included?

Thankee!

**Comment by RoxanneSHS** [comment]
For those who KNOW what that patch did and why it was once needed, the answer is is self explanatory. Those who do not know had better shut up and not discuss matters outside of their limited knowledge.
